# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_auto_20170521_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mill',
            name='product',
            field=models.ManyToManyField(to='manage.Product'),
        ),
    ]
