# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0004_user_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
